env_vars:
  RAY_EXPERIMENTAL_NOSET_ASCEND_RT_VISIBLE_DEVICES: 'true'
  TOKENIZERS_PARALLELISM: 'true'
  NCCL_DEBUG: 'WARN'
  PYTORCH_NPU_ALLOC_CONF: 'expandable_segments:True'
  HCCL_CONNECT_TIMEOUT: '1800'
  HCCL_EXEC_TIMEOUT: '3600'
  HCCL_IF_BASE_PORT: '48000'
  CUDA_DEVICE_MAX_CONNECTIONS: '1'
  HYDRA_FULL_ERROR: '1'
  VLLM_DP_SIZE: '1'
  HCCL_BUFFSIZE: '256'
  VLLM_USE_V1: '1'
  VLLM_VERSION: '0.9.0'
  VLLM_ENABLE_GRAPH_MODE: '0'
  VLLM_ENABLE_MC2: '0'
  HCCL_OP_EXPANSION_MODE: "AIV"
  VLLM_ENABLE_TOPK_OPTIMZE: "1"

#  GLOO_SOCKET_IFNAME: "Your SOCKET IFNAME"
#  TP_SOCKET_IFNAME: "Your SOCKET IFNAME"
#  HCCL_SOCKET_IFNAME: "Your SOCKET IFNAME"