env_vars:
  RAY_EXPERIMENTAL_NOSET_ASCEND_RT_VISIBLE_DEVICES: 'true'
  TOKENIZERS_PARALLELISM: 'true'
  NCCL_DEBUG: 'WARN'
  PYTORCH_NPU_ALLOC_CONF: 'expandable_segments:True'
  HCCL_CONNECT_TIMEOUT: '1800'
  HCCL_EXEC_TIMEOUT: '3600'
