defaults:
  - model:
      - qwen25_32b

megatron_training:
  use_ascend_coc: True
  coc_fused_kernel: True
  coc_parallel_num: 2
  model: qwen25_32b
  use_fused_rmsnorm: true
  use_mcore_models: true
  sequence_parallel: true
  use_flash_attn: true
  no_masked_softmax_fusion: true
  attention_softmax_in_fp32: true
  no_gradient_accumulation_fusion: true
  use_fused_swiglu: true
  use_fused_rotary_pos_emb: true
  bf16: true
  use_distributed_optimizer: true
  tokenizer_type: PretrainedFromHF
  tokenizer_name_or_path: ./Qwen2.5-32B
  global_batch_size: 256
  seq_length: 2048
  save_interval: 50
  train_iters: 200
  stage: ray_dapo
  attention_dropout: 0.0
  hidden_dropout: 0.0
  distributed_backend: nccl
  no_shared_storage: true
  variable_seq_lengths: true
  dataset_additional_keys: ['labels',]
  data_path: ./data
  split: 100,0,0
  no_shuffle: false
  full_shuffle_instruction_dataset: false
  seed: 1
  reset_position_ids: true
  reset_attention_mask: true

actor_config:
  model: qwen25_32b
  micro_batch_size: 1   
  tensor_model_parallel_size: 8
  pipeline_model_parallel_size: 2
  lr: 1e-6
  lr_decay_style: constant
  min_lr: 0
  weight_decay: 0.1
  lr_warmup_fraction: 0.0
  clip_grad: 1.0 #对齐 
  adam_beta1: 0.9
  adam_beta2: 0.95
  finetune: false
  load: ./Qwen2.5-32B-tp8-pp2
  save: ./ckpt
  no_load_optim: false
  no_load_rng: false
  context_parallel_size: 2
  context_parallel_algo: megatron_cp_algo
  cp_attention_mask_type: causal

rl_config:
  blocking: true
  use_remove_padding: true
  actor_max_packing_token_size: 65536
  update_max_packing_token_size: 32768
  use_dynamic_bsz: true
  use_dp_batch_balance: true
  actor_forward_micro_batch_size: 1
  actor_logprob_dispatch_size: 512
  ref_dispatch_size: 512
  reward_dispatch_size: 512
  adv_dispatch_size: 512
  actor_update_dispatch_size: 512
  use_integrated_worker: true
  gamma: 1.0
  lam: 0.95
  adv_estimator: group_norm
  mini_batch_size: 32
  max_prompt_length: 2048
  epochs: 1
  clip_ratio: 0.2
  entropy_coeff: 0.0
  shuffle_mini_batch: false
  n_samples_per_prompt: 16
  rule_reward: true
  verifier_function: ["acc_for_dapo"]
  verifier_weight: [1.0]
  num_cpus_for_local_task: 1.0
  use_tensorboard: true

  # token level loss策略
  token_level_loss: true

  # clip Higher策略
  clip_higher_enable: true
  clip_ratio_low: 0.2
  clip_ratio_high: 0.28

  # 过长response惩罚措施
  overlong_buffer_enable: true
  rollout_max_tokens : 30720
  overlong_buffer: 4096
  overlong_buffer_penalty_factor: 1.0

  # Prompt过滤措施
  filter_groups_enable: false
  filter_groups_metric: acc_for_dapo
  filter_groups_max_batches: -1
  filter_groups_train_batch_size: 32

  actor_resource:
    num_npus: 64

generate_config:
  enforce_eager: True
  trust_remote_code: true
  offload_train_optimizer: true
  offload_train_grad: true
  offload_train_param: true

  # 推理时的并行配置
  infer_tensor_parallel_size: 4
  infer_pipeline_parallel_size: 1
  infer_expert_parallel_size: 1

  # vllm 模型相关设置
  max_num_seqs: 1024
  max_model_len: 32768
  max_num_batched_tokens: 8192
  dtype: "bfloat16"
  gpu_memory_utilization: 0.8

  # 采样配置
  sampling_config:
    seed: 1
    logprobs: 1
    max_tokens: 30720
    top_p: 1.0
    top_k: -1
    min_p: 0.0
    temperature: 1.0
    detokenize: false

