defaults:
  - model:
      - deepseekv3_671b

megatron_training:
  model: deepseekv3_671b
  use_fused_rmsnorm: true
  use_mcore_models: true
  sequence_parallel: true
  use_flash_attn: true
  no_masked_softmax_fusion: true
  attention_softmax_in_fp32: true
  no_gradient_accumulation_fusion: true
  shape_order: BNSD
  use_fused_swiglu: true
  use_fused_rotary_pos_emb: true
  bf16: true
  use_distributed_optimizer: true
  tokenizer_type: PretrainedFromHF
  tokenizer_name_or_path: ./DeepSeek-V3-hf/
  global_batch_size: 128
  seq_length: 1024
  save_interval: 500
  train_iters: 500
  stage: ray_grpo
  attention_dropout: 0.0
  hidden_dropout: 0.0
  distributed_backend: nccl
  no_shared_storage: true
  variable_seq_lengths: true
  dataset_additional_keys: ['labels']
  data_path: ./deepseek/deepscaler
  split: 100,0,0
  no_shuffle: false
  full_shuffle_instruction_dataset: false
  seed: 1
  swap_optimizer: true
  moe_alltoall_overlap_comm: true
  reset_position_ids: true

actor_config:
  model: deepseekv3_671b
  micro_batch_size: 1
  tensor_model_parallel_size: 4
  pipeline_model_parallel_size: 8
  expert_model_parallel_size: 8
  moe_tp_extend_ep: true
  num_layer_list: 7,7,8,8,8,8,8,7
  recompute_granularity: full
  recompute_method: block
  recompute_num_layers: 4
  lr: 1e-6
  lr_decay_style: constant
  weight_decay: 0.01
  lr_warmup_fraction: 0.0
  clip_grad: 1.0
  adam_beta1: 0.9
  adam_beta2: 0.95
  finetune: true
  load: ./ckpt/
  save: ./ckpt/
  no_load_optim: true
  no_load_rng: true

rl_config:
  blocking: true
  use_remove_padding: true
  use_integrated_worker: true
  use_dynamic_bsz: true
  ref_forward_micro_batch_size: 4
  max_packing_token_size: 4096
  gamma: 1.0
  lam: 0.95
  adv_estimator: group_norm
  kl_penalty: low_var_kl
  kl_ctrl_type: fixed
  init_kl_coef: 0.05
  mini_batch_size: 128
  max_prompt_length: 1024
  epochs: 1
  clip_ratio: 0.1
  entropy_coeff: 0
  shuffle_mini_batch: false
  n_samples_per_prompt: 16
  rule_reward: true
  verifier_function: ["math_verify_reward"]
  verifier_weight: [1.0]
  actor_resource:
    num_npus: 256

generate_config:
  trust_remote_code: true
  offload_train_optimizer: false
  offload_train_grad: true
  offload_train_param: true

  # eplb_token_collects: true
  # eplb_token_save_path: ./json_file
  expert_map_path: mindspeed_rl/workers/eplb/expert_map.json


  # 推理时的并行配置
  infer_tensor_parallel_size: 4
  infer_pipeline_parallel_size: 1
  infer_expert_parallel_size: 64
  # vllm 模型相关设置
  max_num_seqs: 32
  max_model_len: 2048
  max_num_batched_tokens: 2048
  dtype: "bfloat16"
  gpu_memory_utilization: 0.7
  enforce_eager: false
  torchair_graph: true
  enable_expert_parallel: true


  # 采样配置
  sampling_config:
    seed: 1
    logprobs: 1
    max_tokens: 512
    top_p: 1.0
    top_k: -1
    min_p: 0
    temperature: 1.0
    detokenize: false
