defaults:
  - model:
      - qwen3_235b_a22b

megatron_training:
  model: qwen3_235b_a22b
  use_flash_attn: true
  shape_order: BNSD
  use_fused_rotary_pos_emb: true
  use_fused_rmsnorm: true
  use_fused_swiglu: true
  no_masked_softmax_fusion: true
  attention_softmax_in_fp32: true
  no_gradient_accumulation_fusion: true
  moe_alltoall_overlap_comm: true

  bf16: true
  sequence_parallel: true
  use_distributed_optimizer: true
  tokenizer_type: PretrainedFromHF
  tokenizer_name_or_path: ./Qwen3-235B-A22B
  global_batch_size: 256
  seq_length: 8192
  save_interval: 100
  train_iters: 200
  stage: ray_grpo
  attention_dropout: 0.0
  init_method_std: 0.01
  hidden_dropout: 0.0
  distributed_backend: nccl
  no_shared_storage: true
  variable_seq_lengths: true
  dataset_additional_keys: ['labels',]
  data_path: ./data
  split: 100,0,0
  swap_optimizer: true
  reset_position_ids: true

actor_config:
  model: qwen3_235b_a22b
  moe_tp_extend_ep: true
  gemm_gradient_accumulation_fusion: true
  micro_batch_size: 1
  expert_model_parallel_size: 4
  tensor_model_parallel_size: 2
  pipeline_model_parallel_size: 16
  noop_layers: "5,95"
  num_layers: 96
  recompute_granularity: full
  recompute_method: block
  recompute_num_layers: 6
  lr: 1e-6
  lr_decay_style: constant
  min_lr: 0.0
  weight_decay: 0.0
  lr_warmup_fraction: 0.0
  clip_grad: 1.0
  adam_beta1: 0.9
  adam_beta2: 0.95
  initial_loss_scale: 4096
  finetune: true
  load: ./ckpt
  save: ./ckpt
  no_load_optim: true
  no_load_rng: true

rl_config:
  use_integrated_worker: true
  ref_forward_micro_batch_size: 2
  actor_forward_micro_batch_size: 2
  mini_batch_size: 256
  n_samples_per_prompt: 8
  use_remove_padding: true
  blocking: true
  gamma: 1.0
  lam: 0.95
  adv_estimator: group_norm
  kl_penalty: low_var_kl
  kl_ctrl_type: fixed
  init_kl_coef: 0.001
  max_prompt_length: 8192
  epochs: 1
  clip_ratio: 0.2
  entropy_coeff: 0
  rule_reward: true
  verifier_function: ["acc_for_dapo"]
  verifier_weight: [1.0]
  verifier_parallel: 4
  log_max_throughput: true
  num_cpus_for_local_task: 1.0
  actor_resource:
    num_npus: 128

generate_config:
  enforce_eager: true
  enable_expert_parallel: true
  # tokenizer相关配置
  trust_remote_code: true

  # 推理时的并行配置
  infer_tensor_parallel_size: 4
  infer_pipeline_parallel_size: 1
  infer_expert_parallel_size: 8

  # vllm 模型相关设置
  max_num_seqs: 64
  max_model_len: 16384
  max_num_batched_tokens: 8192
  dtype: "bfloat16"
  gpu_memory_utilization: 0.85
  enable_prefix_caching: true
  num_scheduler_steps: 1

  offload_train_optimizer: false
  offload_train_grad: true
  offload_train_param: true

  # 采样配置
  sampling_config:
    logprobs: 1
    max_tokens: 8192
    top_p: 0.9
    top_k: 50
    min_p: 0.01
    temperature: 0.9
    detokenize: false