defaults:
  - model:
      - qwen25_7b

sft:
  stage: sft
  is_instruction_dataset: true
  data_path: /data/datasets/pack/alpaca
  reset_position_ids: true
  no_shuffle: true
  model: qwen25_7b
  use_mcore_models: true
  tokenizer_type: PretrainedFromHF
  tokenizer_name_or_path: /data/for_dt/tokenizer/Qwen25-7B
  tokenizer_not_use_fast: false
  tensor_model_parallel_size: 2
  pipeline_model_parallel_size: 2
  sequence_parallel: true
  use_fused_rmsnorm: true
  use_flash_attn: true
  no_masked_softmax_fusion: true
  no_gradient_accumulation_fusion: true
  use_fused_swiglu: true
  use_fused_rotary_pos_emb: true
  bf16: true
  prompt_type: qwen
  variable_seq_lengths: false
  micro_batch_size: 2
  global_batch_size: 8
  train_iters: 5
  seq_length: 4096
  norm_epsilon: 1e-6
  lr: 5e-5
  lr_decay_style: cosine
  min_lr: 1.25e-7
  weight_decay: 1e-1
  lr_warmup_fraction: 0.01
  clip_grad: 1.0
  adam_beta1: 0.9
  adam_beta2: 0.95
  attention_dropout: 0.0
  init_method_std: 0.01
  hidden_dropout: 0.0
  initial_loss_scale: 1
  finetune: true
  no_load_optim: true
  no_load_rng: true
  split: 90,5,5
  log_interval: 1
  save_interval: 10
  eval_interval: 10
  eval_iters: 10
  seed: 1234